---
title: "Learning R Survey Results"
author: "Carl Howe, RStudio"
date: "11/14/2018"
output:
  beamer_presentation: default
  ioslides_presentation:
    css: styles.css
    logo: rstudio.png
    smaller: yes
    widescreen: yes
subtitle: July 31, 2018
---

# Learning R Survey Results

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(googlesheets)
library(tidyverse)
library(RColorBrewer)
library(gendercodeR)

# First, we'll just read in the data and fix all the question names, which in Google Forms, are literally
# the full text of the question. I've put short question names on another sheet of the results Google Sheet, so
# we do the substitution here.

mysheets <- gs_ls() # will authenticate
survey_handle <- gs_title("Learning R Internet Survey")
 # get the survey results
survey <- survey_handle %>%
  gs_read(ws = "Form Responses 1")

## Unfortunately, this read brings in the question text as all the column names. That's not good.
## We'll save them in question_text and put shorter, more friendly names in instead.

survey_questions <- survey_handle %>% gs_read(ws="Question Names")
names(survey) <- survey_questions$Question_name
respondents <- nrow(survey)
survey_save <- survey                # in case I mess up survey, I can check it against this
est <- locale(tz="US/Eastern")
survey$Qtime <- parse_datetime(survey$Qtime, format = "%m/%d/%Y %H:%M:%S", locale=est)

# This learner_type variable defines if someone is a recent R learner or not for faceting
survey <- survey %>% 
  mutate(learner_type = ifelse(Qr_year < 1900, NA, ifelse(Qr_year <= 2016, "Early Learner", "Recent Learner")))

# This codes the open-text gender question into a more friendly form for analysis
survey$Qgender <- tolower(survey$Qgender)
survey_gendercoded <- genderRecode(survey, genderColName = "Qgender", outputColName = "Qgender_coded")

theme_set(theme_bw())

```

## Responses over time

```{r responses over time}
survey <- survey %>% mutate(number_responses = cumsum(!is.na(Qtime)))
ggplot(survey) + 
  geom_line(aes(x=Qtime, y=number_responses)) + 
  ggtitle(sprintf("Survey Responses Over Time (N = %d)",respondents)) + 
  labs(y = "Time", x = "Response Date")

```


## Year Respondents Learned R

```{r Year respondents learned R, echo = TRUE}

ggplot(filter(survey, Qr_year >= 1990)) +
  geom_histogram(aes(Qr_year), binwidth = 1, fill = "blue", color="black") +
  scale_x_continuous(breaks = c(1990, 1995, 2000, 2005, 2010, 2015, 2018)) +
  labs(title = "Year Started Learning R (Histogram)", x="Year", y="Count")
```

## Respondent Ages

```{r Respondent Ages, echo = TRUE}

ggplot(survey) +
  geom_histogram(aes(2018 - Qyear_born), binwidth = 5,  fill = "blue", color="black") +
  scale_x_continuous(breaks = seq(15,80,5)) +
  labs(title = "Respondent Ages (Histogram)", x="Age", y="Count")
```
## Respondent Ages By Learner Type

```{r R Learning Ages By Learner Type, echo = TRUE}

ggplot(filter(survey, !is.na(learner_type)), aes(x = 2018 - Qyear_born, group = learner_type)) +
  geom_density(aes(fill = learner_type), color="black", alpha = 0.5) +
  scale_fill_brewer(palette = "Set1") +
  labs(title = "Respondent Ages (Density Plot)", x="Age", y="Density", fill = "Learner Type")
```

## Difficulty of Learning R based on Learner Type

```{r Ages By Learner Type, echo = TRUE}

ss <- survey %>% filter(!is.na(learner_type) & !is.na(Qr_difficulty_experienced))
ggplot(ss) +
  geom_bar(aes(x = Qr_difficulty_experienced, y = ..prop.., fill = learner_type, group = learner_type),
           position = position_dodge(width = 0.5),
           alpha = 0.5) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_brewer(palette = "Set1") +
  labs(title = "Difficulty in Learning R", x="Respondent Rating (5 = Most Difficult)", y="", fill = "Learner Type")
```
## Respondent Countries

```{r Respondent Countries, echo = TRUE}
countries <- survey %>% count(Qcountry, sort=TRUE) %>% drop_na()
names(countries) <- c("region", "value")
countries <- countries %>% mutate(region = tolower(region))
unknown_countries <- c("singapore", "korea", "south", "serbia and montenegro", "hong kong", "andorra", "bahrain", "christmas island", "macau", "mauritius", "puerto rico", "tanzania")
choro_countries <- countries %>% filter(!(region %in% unknown_countries))
choro_countries <- choro_countries %>% mutate(region = str_replace_all(region, "korea, south", "south korea"))

library(choroplethr)
library(choroplethrMaps)
data(country.map)

# country_choropleth(choro_countries, title = "", legend = "", num_colors = 8,
#  zoom = NULL)

plot_countries <- country.map %>% left_join(choro_countries, by = "region")
ggplot(data = plot_countries, aes(long, lat, group=group)) + 
  geom_polygon(aes(fill = value), color = "gray", size=0.1) +
  scale_fill_gradient(trans = "log10") +
  coord_fixed(1.3) +
  scale_x_continuous(breaks = seq(-150, 150, 60)) +
  scale_y_continuous(breaks = seq(-60, 90, 30), limits = c(-60, 90)) +
  labs(title = "Geographical Distribution of Survey Respondents", x = "", y = "", fill = "Responses")
```