---
title: "Check R Survey Results 2019"
author: "Carl Howe, RStudio"
date: "12/11/2019"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
#options(htmltools.dir.version = FALSE)
library(googledrive)
library(googlesheets4)
library(magrittr)
library(ggplot2)
library(dplyr)
library(stringr)
library(glue)
library(lubridate)
library(RColorBrewer)
library(readr)

column_formats = cols(
 Qtime = col_datetime(format = ""),
 Qr_experience = col_character(),
 Qr_difficulty = col_double(),
 Qr_length_to_success = col_character(),
 Qhow_to_learn_r = col_character(),
 Qreason_to_learn = col_character(),
 Qr_use = col_character(),
 Qtools = col_character(),
 Qobstacles_to_starting = col_character(),
 Qr_year = col_double(),
 Qr_learning_path = col_character(),
 Qr_difficulty = col_double(),
 Qtime_to_proficiency = col_character(),
 Qreason_to_learn = col_character(),
 Qmost_difficult_aspect = col_character(),
 Qr_how_often_used = col_character(),
 Qused_for = col_character(),
 Qr_enjoyment = col_double(),
 Qrecommend = col_double(),
 Qr_tools = col_character(),
 Qtidyverse_learning = col_character(),
 Qtidyverse_today = col_character(),
 Qlike_best = col_character(),
 Qlike_least = col_character(),
 Qr_problems = col_character(),
 Qr_discover_packages = col_character(),
 Qr_share = col_character(),
 Qr_change = col_character(),
 Qrobot_test = col_character(),
 Qrmarkdown = col_character(),
 Qrmarkdown_apps = col_character(),
 Qrmarkdown_change = col_character(),
 Qshiny = col_character(),
 Qshiny_change  = col_character(),
 Qpython_use = col_character(),
 Qpython_apps = col_character(),
 Qpython_enjoy = col_double(),
 Qpython_recommend = col_double(),
 Qpython_change = col_character(),
 Qlanguages  = col_character(),
 Qfirst_language = col_character(),
 Qyear_born = col_double(),
 Qgender  = col_character(),
 Qethnicity  = col_character(),
 Qdegree  = col_character(),
 Qcountry  = col_character(),
 Qindustry  = col_character(),
 Qtitle  = col_character(),
 Qwork_title  = col_character(),
 Qevents  = col_character(),
 Qhear  = col_character()
)

googledrive::drive_deauth()
googledrive::drive_auth(email = "carl@rstudio.com") # if we don't do this explicitly, auth doesn't really work for me.
english_sheet <- drive_get("2019 English R Community Survey Responses", col_types = column_formats)
english_survey <- sheets_read(english_sheet, sheet = "Form Responses 1")
spanish_sheet <- drive_get("2019 Spanish R Community Survey Responses")
spanish_survey <- sheets_read(spanish_sheet, sheet = "Form Responses 1")
print(glue("Number of English responses is {nrow(english_survey)}"))
print(glue("Number of Spanish responses is {nrow(spanish_survey)}"))
```
## Response graph

```{r graph_all}
english_timestamps <- english_survey %>% select(Timestamp) %>% mutate(language = "English", unit = 1)
spanish_timestamps <- spanish_survey %>% select(Timestamp) %>% mutate(language = "Spanish", unit = 1)
timestamps <- rbind(english_timestamps, spanish_timestamps)
timestamps <- timestamps %>% 
  arrange(Timestamp) %>% 
  mutate(responses = cumsum(unit)) %>% 
  ungroup()
theme_set(theme_minimal())
ggplot(timestamps, aes(x = Timestamp, y = responses, color = language, group = unit)) + 
  geom_point(alpha = 0.2) +
  geom_smooth(method = "loess", se=FALSE, color = "blue", alpha=1.0) +
  scale_color_brewer(palette = "Set2") +
  labs(title = "All R Survey Responses", x = "Date", y = "Total Responses", color = "Language")
```

## Response by language

```{r graph_by_language}

faceted_timestamps <- rbind(english_timestamps, spanish_timestamps)
faceted_timestamps <- faceted_timestamps %>% 
  arrange(Timestamp) %>%
  group_by(language) %>%
  mutate(responses = cumsum(unit))
theme_set(theme_minimal())
ggplot(faceted_timestamps, aes(x = Timestamp, y = responses, color = language, group = language)) + 
  geom_point(alpha = 0.2) +
  geom_smooth(method = "loess", se=FALSE, alpha = 1.0) +
  scale_color_brewer(palette = "Set2") +
  labs(title = "R Survey Responses by Language", x = "Date", y = "Total Responses", color = "Language")
```

```{r write_files}
english_survey_names <- names(english_survey)
spanish_survey_names <- names(spanish_survey)
write_tsv(tibble(english_survey_names), "data/2019-english-survey-names.tsv")
write_tsv(tibble(spanish_survey_names), "data/2019-spanish-survey-names.tsv")
write_tsv(data.frame(spanish_survey), path=glue("data/2019-spanish-survey-{today()}.tsv"))
write_tsv(tibble(english_survey), path=glue("data/2019-english-survey-{today()}.tsv"))
```

