---
title: "Check R Survey Results 2019"
author: "Carl Howe, RStudio"
date: "12/11/2019"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
#options(htmltools.dir.version = FALSE)
library(googledrive)
library(googlesheets4)
library(magrittr)
library(ggplot2)
library(dplyr)
library(stringr)
library(glue)
library(lubridate)
library(RColorBrewer)
library(readr)

## Read in the short column names and their English and Spanish equivalents

combined_survey_names <- read_tsv("data/2020-combined-survey-names.tsv")
googledrive::drive_deauth()
googledrive::drive_auth(email="carl@rstudio.com", scopes = "https://www.googleapis.com/auth/drive.readonly")
english_sheet <- drive_get("2020 English R Community Survey Responses")
english_survey <- range_read(ss=english_sheet, col_names = combined_survey_names$question_name, col_types="c")
spanish_sheet <- drive_get("2020 Spanish R Community Survey Responses")
spanish_survey <- range_read(spanish_sheet, col_names = combined_survey_names$question_name, col_types = "c")
print(glue("Total responses are {nrow(english_survey) + nrow(spanish_survey)}"))
print(glue("Number of English responses is {nrow(english_survey)}"))
print(glue("Number of Spanish responses is {nrow(spanish_survey)}"))
```
## Response graph

```{r graph_all}
english_timestamps <- english_survey %>% select(Timestamp) %>% mutate(language = "English", unit = 1)
spanish_timestamps <- spanish_survey %>% select(Timestamp) %>% mutate(language = "Spanish", unit = 1)
timestamps <- rbind(english_timestamps, spanish_timestamps)
timestamps <- timestamps %>% 
  arrange(Timestamp) %>% 
  mutate(responses = cumsum(unit)) %>% 
  ungroup()
theme_set(theme_minimal())
ggplot(timestamps, aes(x = Timestamp, y = responses, color = language, group = unit)) + 
  geom_point(alpha = 1.0) +
#  geom_smooth(method = "loess", se=FALSE, color = "blue", alpha=0.1) +
  scale_color_brewer(palette = "Set2") +
  labs(title = paste0("All R Survey Responses as of ", date()), x = "Date", y = "Total Responses", color = "Language")
ggsave("plots/survey-progress.pdf")
```

## Response by language

```{r graph_by_language}

faceted_timestamps <- rbind(english_timestamps, spanish_timestamps)
faceted_timestamps <- faceted_timestamps %>% 
  arrange(Timestamp) %>%
  group_by(language) %>%
  mutate(responses = cumsum(unit))
theme_set(theme_minimal())
ggplot(faceted_timestamps, aes(x = Timestamp, y = responses, color = language, group = language)) + 
  geom_point(alpha = 1.0) +
#  geom_smooth(method = "loess", se=FALSE, alpha = 1.0) +
  scale_color_brewer(palette = "Set2") +
  labs(title = paste0("R Survey Responses by Language as of ", date()), x = "Date", y = "Total Responses", color = "Language")
ggsave("plots/survey-progress-by-language.pdf")
```

```{r write_files}
english_survey_names <- names(english_survey)
spanish_survey_names <- names(spanish_survey)
write_tsv(tibble(english_survey_names), "data/2020-english-survey-names.tsv")
write_tsv(tibble(spanish_survey_names), "data/2020-spanish-survey-names.tsv")
# combined_survey_names <- tibble("english" = english_survey_names, "spanish" = spanish_survey_names)
combined_survey_names <- read_tsv("data/2020-combined-survey-names.tsv")
# write_tsv(combined_survey_names, "data/2020-combined-survey-names.tsv")
names(spanish_survey) <- combined_survey_names$question_name
names(english_survey) <- combined_survey_names$question_name
write_tsv(tibble(spanish_survey), file=glue("data/2020-spanish-survey-final.tsv"))
write_tsv(tibble(english_survey), file=glue("data/2020-english-survey-final.tsv"))
```

