---
title: "Preprocess Google Sheets Responses for Survey Analysis"
author: "Carl Howe, RStudio"
date: "2021-01-29"
output: html_document
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
#options(htmltools.dir.version = FALSE)
library(googledrive)
library(googlesheets4)
library(magrittr)
library(ggplot2)
library(dplyr)
library(stringr)
library(glue)
library(lubridate)
library(RColorBrewer)
library(readr)

## Read in the short column names and their English and Spanish equivalents

# This file has the long English and Spanish question texts and their equivalent short names.

## As it turns out, we have to be very careful here. While the Google Sheets with English and Spanish responses have
## most of their columns in the same order, not all are. That means we have to read in the columns and assign different
## column names. We'll rearrange the columns for both surveys into the same order later in the code.

## We'll also do some simple type checking by specifying the column types for each language. The column type spec
## will specify the column order AND will throw parse errors if we somehow have gotten things wrong.

english_column_formats <- cols(
  Qtime = col_datetime(format = "%Y/%m/%d %H:%M:%S"),
  Qr_experience = col_character(),
  Qhow_to_learn_r = col_character(),
  Qreason_to_learn = col_character(),
  Qr_use = col_character(),
  Qtools = col_character(),
  Qobstacles_to_starting = col_character(),
  Qr_year = col_double(),
  Qr_learning_path = col_character(),
  Qr_reason_experienced = col_character(),
  Qmost_difficult_aspect = col_character(),
  Qr_how_often_used = col_character(),
  Qr_OS = col_character(),
  Qused_for = col_character(),
  Qr_enjoyment = col_double(),
  Qrecommend = col_double(),
  Qtools_with_r = col_character(),
  Qtidyverse_learning = col_character(),
  Qtidyverse_today = col_character(),
  Qlike_best = col_character(),
  Qlike_least = col_character(),
  Qr_problems = col_character(),
  Qr_discover_packages = col_character(),
  Qr_share = col_character(),
  Qr_change = col_character(),
  Qrobot_test = col_character(),
  Qrmarkdown = col_character(),
  Qrmarkdown_apps = col_character(),
  Qrmarkdown_change = col_character(),
  Qshiny = col_character(),
  Qshiny_use = col_character(),
  Qshiny_change = col_character(),
  Qpython_use = col_character(),
  Qpython_apps = col_character(),
  Qpython_tools = col_character(),
  Qpython_enjoy = col_double(),
  Qpython_recommend = col_double(),
  Qpython_change = col_character(),
  Qcoding_languages = col_character(),
  Qfirst_language = col_character(),
  Qyear_born = col_double(),
  Qgender = col_character(),
  Qethnicity = col_character(),
  Qdegree = col_character(),
  Qcountry = col_character(),
  Qindustry = col_character(),
  Qtitle = col_character(),
  Qwork_title = col_character(),
  Qteam_r_users = col_character(),
  Qr_community = col_character(),
  Qevents = col_character(),
  Qhear = col_character()
)

spanish_column_formats <- cols(
  Qtime = col_datetime(format = "%Y/%m/%d %H:%M:%S"),
  Qr_experience = col_character(),
  Qhow_to_learn_r = col_character(),
  Qreason_to_learn = col_character(),
  Qr_use = col_character(),
  Qtools = col_character(),
  Qobstacles_to_starting = col_character(),
  Qr_year = col_double(),
  Qr_learning_path = col_character(),
  Qr_reason_experienced = col_character(),
  Qmost_difficult_aspect = col_character(),
  Qr_how_often_used = col_character(),
  Qr_OS = col_character(),
  Qused_for = col_character(),
  Qr_enjoyment = col_double(),
  Qrecommend = col_double(),
  Qtools_with_r = col_character(),
  Qtidyverse_learning = col_character(),
  Qtidyverse_today = col_character(),
  Qlike_best = col_character(),
  Qlike_least = col_character(),
  Qr_problems = col_character(),
  Qr_discover_packages = col_character(),
  Qr_share = col_character(),
  Qr_change = col_character(),
  Qrobot_test = col_character(),
  Qrmarkdown = col_character(),
  Qrmarkdown_apps = col_character(),
  Qrmarkdown_change = col_character(),
  Qshiny = col_character(),
  Qshiny_use = col_character(),
  Qshiny_change = col_character(),
  Qpython_use = col_character(),
  Qpython_apps = col_character(),
  Qpython_enjoy = col_double(),
  Qpython_recommend = col_double(),
  Qpython_tools = col_character(),
  Qpython_change = col_character(),
  Qcoding_languages = col_character(),
  Qfirst_language = col_character(),
  Qyear_born = col_double(),
  Qgender = col_character(),
  Qethnicity = col_character(),
  Qdegree = col_character(),
  Qcountry = col_character(),
  Qindustry = col_character(),
  Qtitle = col_character(),
  Qwork_title = col_character(),
  Qteam_r_users = col_character(),
  Qr_community = col_character(),
  Qevents = col_character(),
  Qhear = col_character()
)


googledrive::drive_deauth()
googledrive::drive_auth(email="carl@rstudio.com", scopes = "https://www.googleapis.com/auth/drive.readonly")
combined_survey_names <- read_tsv("data/2020-combined-survey-names3.tsv")

english_sheet <- drive_get("2020 English R Community Survey Responses")
english_survey <- range_read(ss=english_sheet,
                             col_names = combined_survey_names$english_name, 
                             col_types = paste0(combined_survey_names$english_type, collapse=""), skip=1)
spanish_sheet <- drive_get("2020 Spanish R Community Survey Responses")
spanish_survey <- range_read(spanish_sheet, 
                             col_names = combined_survey_names$spanish_name, 
                             col_types = paste0(combined_survey_names$spanish_type, collapse=""), skip=1)
print(glue("Total responses are {nrow(english_survey) + nrow(spanish_survey)}"))
print(glue("Number of English responses is {nrow(english_survey)}"))
print(glue("Number of Spanish responses is {nrow(spanish_survey)}"))
```
## Response graph

```{r graph_all}
english_timestamps <- english_survey %>% select(Qtime) %>% mutate(language = "English", unit = 1)
spanish_timestamps <- spanish_survey %>% select(Qtime) %>% mutate(language = "Spanish", unit = 1)
timestamps <- rbind(english_timestamps, spanish_timestamps)
timestamps <- timestamps %>% 
  arrange(Qtime) %>% 
  mutate(responses = cumsum(unit)) %>% 
  ungroup()
theme_set(theme_minimal())
ggplot(timestamps, aes(x = Qtime, y = responses, color = language, group = unit)) + 
  geom_point(alpha = 1.0) +
#  geom_smooth(method = "loess", se=FALSE, color = "blue", alpha=0.1) +
  scale_color_brewer(palette = "Set2") +
  scale_x_datetime() +
  labs(title = paste0("All R Survey Responses as of ", date()), x = "Date", y = "Total Responses", color = "Language")
ggsave("plots/survey-progress.pdf")
```

## Response by language

```{r graph_by_language}

faceted_timestamps <- rbind(english_timestamps, spanish_timestamps)
faceted_timestamps <- faceted_timestamps %>% 
  arrange(Qtime) %>%
  group_by(language) %>%
  mutate(responses = cumsum(unit))
theme_set(theme_minimal())
ggplot(faceted_timestamps, aes(x = Qtime, y = responses, color = language, group = language)) + 
  geom_point(alpha = 1.0) +
#  geom_smooth(method = "loess", se=FALSE, alpha = 1.0) +
  scale_color_brewer(palette = "Set2") +
  scale_x_datetime() +
  labs(title = paste0("R Survey Responses by Language as of ", date()), x = "Date", y = "Total Responses", color = "Language")
ggsave("plots/survey-progress-by-language.pdf")
```

```{r write_files}
## this next statement is to reorder the spanish survey columns to match the english survey column order.
## that will allow us to rbind the two together
spanish_survey2 <- spanish_survey %>% 
  select(!!combined_survey_names$english_name) %>% 
  mutate(language = "Spanish")
english_survey2 <- english_survey %>% 
   select(!!combined_survey_names$english_name) %>% 
   mutate(language = "English")
combined_survey2 <- rbind(english_survey2, spanish_survey2)
write_tsv(spanish_survey2, file=glue("data/2020-spanish-survey-final.tsv"))
write_tsv(english_survey2, file=glue("data/2020-english-survey-final.tsv"))
write_tsv(combined_survey2, file=glue("data/2020-combined-survey-final.tsv"))
```

